# Use an official Ubuntu base image
FROM ubuntu:20.04

# Install necessary packages
RUN apt-get update && apt-get install -y g++ make

# Copy the server source code
COPY server.cpp /app/server.cpp
COPY blockChain.h /app/blockChain.h
COPY blockChain.cpp /app/blockChain.cpp

# Set the working directory
WORKDIR /app

# Compile the server application
RUN g++ server.cpp blockChain.cpp -o server -lpthread

# Create the directory for the pipe
RUN mkdir -p /mnt/mta

# Expose any ports the server might use
EXPOSE 12345

# Command to run the server application
CMD ["./server"]
