# Use an official Ubuntu base image
FROM ubuntu:20.04

# Install necessary packages
RUN apt-get update && apt-get install -y g++ make

# Copy the miner source code
COPY miner.cpp /app/miner.cpp
COPY blockChain.h /app/blockChain.h
COPY blockChain.cpp /app/blockChain.cpp

# Set the working directory
WORKDIR /app

# Compile the miner application
RUN g++ miner.cpp blockChain.cpp -o miner -lpthread

# Create the directory for the pipe
RUN mkdir -p /mnt/mta

# Command to run the miner application
CMD ["./miner"]